export const contactPage = {
  eyebrow: 'Contact',
  titleThin: 'Got too many',
  titleBold: 'moving pieces?',
  lede: 'Tell me what keeps getting lost, repeated, or stuck. I can help organize the work, document the process, or support the follow-through around it.',
  faqEyebrow: 'FAQs',
  faqTitle: 'Quick answers',
  faqSub: 'Still have a question? Send me a note.',
  cardTitle: 'Tell me what you need',
  cardBody: 'A few lines about the workflow, documentation problem, or recurring support you need is enough to start.',
}

export const contactForm = {
  first: 'First name',
  last: 'Last name',
  email: 'Email',
  message: 'Tell me about the work',
  phFirst: 'First name',
  phLast: 'Last name',
  phEmail: 'you@yourbusiness.com',
  phMessage: 'What is getting lost, repeated, delayed, or hard to maintain? What tools or documents are involved?',
  send: 'Send message',
  hint: 'This form opens your own email app. Nothing is sent to or stored on this site.',
  error: 'Add your name, a real email, and a short note.',
  sentTitle: 'Your mail app has it.',
  sentBody: 'The message is laid out and addressed. Press send there and it is on its way.',
  noMailApp: 'No mail app opened? Write to',
  copy: 'Copy message',
  copied: 'Copied',
  again: 'Write another',
}
